name: finalproject
description: An e-commerce app b/w factories and auditors.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  swipe: any
  google_fonts: ^4.0.4
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.1
  cloud_firestore:
  firebase_core:
  firebase_auth:
  go_router:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
